name: Snyk Security

on:
  push:
    branches: ["master" ]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read #
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - name: Set up Snyk CLI 
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Snyk Code test
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
      - name: Snyk Run
        run: snyk test
      - name : Snyc code run
        run: snyk code test
        continue-on-error: true

